# Generated by Django 2.2.1 on 2019-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190916_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ask_order',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='bid_order',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
