# Generated by Django 2.2.1 on 2019-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190916_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Filled', 'Filled')], default='Open', max_length=9),
        ),
    ]
