# Generated by Django 2.2.3 on 2019-09-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190919_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coin_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], default='ETH', max_length=3),
        ),
    ]
